#spring.application.name=spring-boot-seminar-9-ag
server:
  port: 8765

spring:
  application:
    name: spring-boot-seminar-9-ag
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8081/
          predicates:
            - Path=/serviceA/**
        - id: Microservice2
          uri: http://localhost:8082/
          predicates:
            - Path=/serviceB/