#spring.application.name=spring-boot-lesson-5

spring:
  application:
    name: spring-boot-lesson-5
  datasource:
    url: jdbc:h2:mem:test
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true #??????????? sql ???????, ??????? ???????????
    hibernate:
      ddl-auto: #???, ??????? ????? ??????????? ??? ?????? ? ????? ??????
