#spring.application.name=springLesson4
#spring.thymeleaf.check-template-location=true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mynewdb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update